import { z } from "zod";

const listingTierSchema = z.enum(["free", "featured", "premium"]);

export const serviceProviderRowSchema = z
  .object({
    id: z.string().uuid(),
    slug: z.string(),
    display_name: z.string(),
    category_slug: z.string(),
    city_slug: z.string(),
    phone: z.string(),
    email: z.string().nullable().optional(),
    whatsapp: z.string().nullable().optional(),
    bio: z.string().nullable().optional(),
    years_experience: z.number().nullable().optional(),
    licensed: z.boolean().optional(),
    status: z.enum(["pending", "approved", "rejected", "paused"]),
    featured: z.boolean().optional(),
    contact_clicks: z.number().optional(),
    created_at: z.string(),
    updated_at: z.string().optional(),
    listing_tier: listingTierSchema.optional(),
    verified: z.boolean().optional(),
    insurance_verified: z.boolean().optional(),
    license_number: z.string().nullable().optional(),
    website: z.string().nullable().optional(),
    portfolio_urls: z.array(z.string()).nullable().optional(),
    business_hours: z.string().nullable().optional(),
    response_time: z.string().nullable().optional(),
    jobs_completed: z.number().optional(),
    min_callout_fee: z.string().nullable().optional(),
    emergency_available: z.boolean().optional(),
    avg_rating: z.coerce.number().optional(),
    review_count: z.number().optional(),
    requested_plan: z.string().nullable().optional(),
    owner_user_id: z.string().uuid().nullable().optional(),
  })
  .transform((p) => ({
    ...p,
    email: p.email ?? null,
    whatsapp: p.whatsapp ?? null,
    bio: p.bio ?? null,
    years_experience: p.years_experience ?? null,
    licensed: p.licensed ?? false,
    featured: p.featured ?? false,
    contact_clicks: p.contact_clicks ?? 0,
    listing_tier: p.listing_tier ?? ("free" as const),
    verified: p.verified ?? false,
    insurance_verified: p.insurance_verified ?? false,
    portfolio_urls: p.portfolio_urls ?? [],
    jobs_completed: p.jobs_completed ?? 0,
    emergency_available: p.emergency_available ?? false,
    avg_rating: Number(p.avg_rating ?? 0),
    review_count: p.review_count ?? 0,
    requested_plan: p.requested_plan ?? "free",
    owner_user_id: p.owner_user_id ?? null,
  }));
